name: Migrate Python 2 to 3

on:
  push:

jobs:
  run-migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Equivalence Converter
        uses: anand-esc/MIGRATE@v1.0.0
        with:
          target-path: '.'
          fail-on-mismatch: 'true'
          auto-commit: 'true'
